INSERT INTO data_from_users (id, city, address) VALUES (1, 'Lublin', 'Turystyczna 9');
INSERT INTO data_from_users (id, city, address) VALUES (2, 'Lublin', 'szmaragdowa 24');
INSERT INTO data_from_users (id, city, address) VALUES (3, 'Lublin', 'Pana Balcera 6');
INSERT INTO data_from_users (id, city, address) VALUES (4, 'Lublin', 'Kaprysowa 4');
INSERT INTO data_from_users (id, city, address) VALUES (5, 'Lublin', 'Nałkowskich 119a');
INSERT INTO data_from_users (id, city, address) VALUES (6, 'Lublin', 'Sasankowa 8/1A');
INSERT INTO data_from_users (id, city, address) VALUES (7, 'Lublin', 'Lubartowska 36');
INSERT INTO data_from_users (id, city, address) VALUES (8, 'Lublin', 'Konopnicka 9');
INSERT INTO data_from_users (id, city, address) VALUES (9, 'Lublin', 'Puławska 26');
INSERT INTO data_from_users (id, city, address) VALUES (10, 'Lublin', 'Staffa 20a');
INSERT INTO data_from_users (id, city, address) VALUES (11, 'Lublin', 'Witolda Chodźki 25');
INSERT INTO data_from_users (id, city, address) VALUES (12, 'Lublin', 'Mieczysławy Cwiklińskiej 8');
INSERT INTO data_from_users (id, city, address) VALUES (13, 'Lublin', 'Cypriana Godebskiego 3');
INSERT INTO data_from_users (id, city, address) VALUES (14, 'Lublin', 'Przybylskiego 26');
INSERT INTO data_from_users (id, city, address) VALUES (15, 'Lublin', 'Gajowa 6');
INSERT INTO data_from_users (id, city, address) VALUES (16, 'Lublin', 'Kawaleryjska 20a');
INSERT INTO data_from_users (id, city, address) VALUES (17, 'Lublin', 'Witolda Chodźki 19');
INSERT INTO data_from_users (id, city, address) VALUES (18, 'Lublin', 'Bukowa  15');
INSERT INTO data_from_users (id, city, address) VALUES (19, 'Lublin', 'Montażowa  14');
INSERT INTO data_from_users (id, city, address) VALUES (20, 'Lublin', 'Narutowicza 23');
INSERT INTO data_from_users (id, city, address) VALUES (21, 'Lublin', 'Akademicka 1');
INSERT INTO data_from_users (id, city, address) VALUES (22, 'Lublin', 'Ks. Jerzego Popiełuszki 35A');
INSERT INTO data_from_users (id, city, address) VALUES (23, 'Lublin', 'Dulęby 1');
INSERT INTO data_from_users (id, city, address) VALUES (24, 'Lublin', 'Ułanów 35');
INSERT INTO data_from_users (id, city, address) VALUES (25, 'Lublin', 'Unicka 4');
INSERT INTO data_from_users (id, city, address) VALUES (26, 'Lublin', 'Konrada Wallenroda 4c');
INSERT INTO data_from_users (id, city, address) VALUES (27, 'Lublin', 'Północna  6');
INSERT INTO data_from_users (id, city, address) VALUES (28, 'Lublin', 'Kunickiego 55');
INSERT INTO data_from_users (id, city, address) VALUES (29, 'Lublin', 'Narutowicza 79');
INSERT INTO data_from_users (id, city, address) VALUES (30, 'Lublin', 'Nałkowskich 107');
INSERT INTO data_from_users (id, city, address) VALUES (31, 'Lublin', 'Lubartowska  22');
INSERT INTO data_from_users (id, city, address) VALUES (32, 'Lublin', 'Władysława Kunickiego 7');
INSERT INTO data_from_users (id, city, address) VALUES (33, 'Lublin', 'Nałęczowska 18');
INSERT INTO data_from_users (id, city, address) VALUES (34, 'Lublin', 'Głęboka 8A');
INSERT INTO data_from_users (id, city, address) VALUES (35, 'Lublin', 'Spółdzielczości Pracy 43');
INSERT INTO data_from_users (id, city, address) VALUES (36, 'Lublin', 'Sikorskiego  1');
INSERT INTO data_from_users (id, city, address) VALUES (37, 'Lublin', 'Fulmana  7');
INSERT INTO data_from_users (id, city, address) VALUES (38, 'Lublin', 'J. Piłsudskiego 10');
INSERT INTO data_from_users (id, city, address) VALUES (39, 'Lublin', 'Krańcowa 107');
INSERT INTO data_from_users (id, city, address) VALUES (40, 'Lublin', 'Nadbystrzycka 100');
INSERT INTO data_from_users (id, city, address) VALUES (41, 'Lublin', 'Świętoduska  18');
INSERT INTO data_from_users (id, city, address) VALUES (42, 'Lublin', 'Krakowskie Przedmieście 57');
INSERT INTO data_from_users (id, city, address) VALUES (43, 'Lublin', 'Daszyńskiego 4a');
INSERT INTO data_from_users (id, city, address) VALUES (44, 'Lublin', '3 Maja  10');
INSERT INTO data_from_users (id, city, address) VALUES (45, 'Lublin', 'Wertera 68');
INSERT INTO data_from_users (id, city, address) VALUES (46, 'Lublin', 'Chopina  11');
INSERT INTO data_from_users (id, city, address) VALUES (47, 'Lublin', 'Obywatelska  ');
INSERT INTO data_from_users (id, city, address) VALUES (48, 'Lublin', 'M.C. Skłodowskiej  6');
INSERT INTO data_from_users (id, city, address) VALUES (49, 'Lublin', '1 Maja 16F');
INSERT INTO data_from_users (id, city, address) VALUES (50, 'Lublin', 'Północn 5');
INSERT INTO data_from_users (id, city, address) VALUES (51, 'Lublin', 'FIRLEJOWSKA 2');
INSERT INTO data_from_users (id, city, address) VALUES (52, 'Lublin', 'Kołłštaja 2');
INSERT INTO data_from_users (id, city, address) VALUES (53, 'Lublin', 'Krakowskie Przedmieście 74');
INSERT INTO data_from_users (id, city, address) VALUES (54, 'Lublin', 'Górska  7');
INSERT INTO data_from_users (id, city, address) VALUES (55, 'Lublin', 'Baśniowa  8');
INSERT INTO data_from_users (id, city, address) VALUES (56, 'Lublin', 'Nadbystrzycka 39');
INSERT INTO data_from_users (id, city, address) VALUES (57, 'Lublin', 'Nadstawna 4');
INSERT INTO data_from_users (id, city, address) VALUES (58, 'Lublin', 'Bernardyńska  8');
INSERT INTO data_from_users (id, city, address) VALUES (59, 'Lublin', 'Domeyki 1');
INSERT INTO data_from_users (id, city, address) VALUES (60, 'Lublin', 'Śliwińskiego  19');
INSERT INTO data_from_users (id, city, address) VALUES (61, 'Lublin', 'Diamentowa 19');
INSERT INTO data_from_users (id, city, address) VALUES (62, 'Lublin', 'Magnoliowa 1');
INSERT INTO data_from_users (id, city, address) VALUES (63, 'Lublin', 'Zemborzycka 78');
INSERT INTO data_from_users (id, city, address) VALUES (64, 'Lublin', 'Hetmanska 20');
INSERT INTO data_from_users (id, city, address) VALUES (65, 'Lublin', 'Jana Sawy  1A');
INSERT INTO data_from_users (id, city, address) VALUES (66, 'Lublin', 'Chojny 1');
INSERT INTO data_from_users (id, city, address) VALUES (67, 'Lublin', 'Sapiehy 24');
INSERT INTO data_from_users (id, city, address) VALUES (68, 'Lublin', 'Sapiehy 2');
INSERT INTO data_from_users (id, city, address) VALUES (69, 'Lublin', 'Hutnicza 1');
INSERT INTO data_from_users (id, city, address) VALUES (70, 'Lublin', 'Mełgiewska 4A');
INSERT INTO data_from_users (id, city, address) VALUES (71, 'Lublin', 'Bursztynowa 39');
INSERT INTO data_from_users (id, city, address) VALUES (72, 'Lublin', 'Ruciana  4');
INSERT INTO data_from_users (id, city, address) VALUES (73, 'Lublin', 'Króla Rogera 4A');
INSERT INTO data_from_users (id, city, address) VALUES (74, 'Lublin', 'Al. Spółdzielczości Pracy 87');
INSERT INTO data_from_users (id, city, address) VALUES (75, 'Lublin', 'Chemiczna 19');
INSERT INTO data_from_users (id, city, address) VALUES (76, 'Lublin', 'Zagłoby 2');
INSERT INTO data_from_users (id, city, address) VALUES (77, 'Lublin', 'Gesia 16');